# Generated by Django 5.0.1 on 2024-01-19 22:26

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Centre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('designation', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_cl', models.CharField(auto_created=True, max_length=10, unique=True)),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=100)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('credit', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Doit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_Code', models.CharField(max_length=20)),
                ('fk_Num_P', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('Code_E', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Nom_E', models.CharField(max_length=100)),
                ('Prenom_E', models.CharField(max_length=100)),
                ('Adresse_E', models.CharField(max_length=200)),
                ('Tel_E', models.CharField(max_length=15)),
                ('Salaire_par_jour', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fk_Code_CE', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pointage',
            fields=[
                ('Num_P', models.AutoField(primary_key=True, serialize=False)),
                ('Date_P', models.DateTimeField()),
                ('Pointe', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code_P', models.CharField(auto_created=True, max_length=10)),
                ('Desiginiation_P', models.CharField(max_length=10)),
                ('Quantity', models.IntegerField()),
                ('prix_Unit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PV',
            fields=[
                ('Date_PV', models.DateTimeField(primary_key=True, serialize=False)),
                ('Text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeM', models.CharField(max_length=10, unique=True)),
                ('designation', models.CharField(max_length=50)),
                ('Qstock', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_S', models.CharField(max_length=10, unique=True)),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=100)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('balance', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=100)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('daily_salary', models.FloatField()),
                ('centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.centre')),
            ],
        ),
        migrations.CreateModel(
            name='Massrouf',
            fields=[
                ('Num_MAS', models.AutoField(primary_key=True, serialize=False)),
                ('Date_M', models.DateTimeField()),
                ('Credit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fk_Code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.employe')),
            ],
        ),
        migrations.CreateModel(
            name='EnRapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_Code_E', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.employe')),
                ('fk_Date_PV', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.pv')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(auto_created=True, max_length=10, unique=True)),
                ('quantity', models.IntegerField()),
                ('name_P', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.rawmaterial')),
            ],
        ),
        migrations.CreateModel(
            name='Achat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pur', models.CharField(auto_created=True, max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.FloatField()),
                ('reglement', models.FloatField()),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.rawmaterial')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_tr', models.CharField(auto_created=True, max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True, unique=True)),
                ('quantity', models.IntegerField()),
                ('centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.centre')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.rawmaterial')),
            ],
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale', models.CharField(auto_created=True, max_length=10)),
                ('num_vente', models.IntegerField(auto_created=True)),
                ('quantity', models.IntegerField(max_length=10)),
                ('prix_U', models.FloatField()),
                ('p_credits', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.client')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.rawmaterial')),
            ],
        ),
        migrations.CreateModel(
            name='VenteP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_V', models.IntegerField()),
                ('Date_v', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField()),
                ('prix_Unit', models.FloatField()),
                ('p_credits', models.FloatField()),
                ('code_cl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.client')),
                ('code_p', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.product')),
            ],
        ),
    ]
