# Generated by Django 5.0.1 on 2024-01-21 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventep',
            name='id',
        ),
        migrations.AlterField(
            model_name='ventep',
            name='num_V',
            field=models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
