# Generated by Django 5.0 on 2024-01-22 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_remove_ventep_id_alter_ventep_num_v'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventep',
            name='code_p',
        ),
        migrations.RemoveField(
            model_name='ventep',
            name='code_cl',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='VenteP',
        ),
    ]
