# Generated by Django 5.0 on 2024-01-22 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_remove_ventep_code_p_remove_ventep_code_cl_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('Code_P', models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False, unique=True)),
                ('Desiginiation_P', models.CharField(max_length=10)),
                ('Quantity', models.IntegerField()),
                ('prix_Unit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VenteP',
            fields=[
                ('num_V', models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False, unique=True)),
                ('Date_v', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField()),
                ('prix_Unit', models.FloatField()),
                ('p_credits', models.FloatField()),
                ('code_cl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.client')),
                ('code_p', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.product')),
            ],
        ),
    ]
