# Generated by Django 5.0.1 on 2024-01-23 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_product_ventep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='id',
        ),
        migrations.AlterField(
            model_name='supplier',
            name='code_S',
            field=models.CharField(auto_created=True, editable=False, max_length=40, primary_key=True, serialize=False, unique=True),
        ),
    ]
