# Generated by Django 5.0.1 on 2024-01-20 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_rawmaterial_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achat',
            name='pur',
            field=models.IntegerField(auto_created=True, max_length=10),
        ),
    ]
