# Generated by Django 5.0.1 on 2024-01-20 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_achat_pur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achat',
            name='id',
        ),
        migrations.AlterField(
            model_name='achat',
            name='pur',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
