# Generated by Django 5.0.1 on 2024-01-23 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_remove_supplier_id_alter_supplier_code_s'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='code_S',
            field=models.CharField(auto_created=True, max_length=10, primary_key=True, serialize=False),
        ),
    ]
