# Generated by Django 5.0.1 on 2024-01-23 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_supplier_code_s'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='code_S',
            field=models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
