# Generated by Django 5.0.1 on 2024-01-20 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_remove_achat_id_alter_achat_pur'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achat',
            old_name='pur',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='designation',
            field=models.CharField(max_length=50),
        ),
    ]
