# Generated by Django 5.0.1 on 2024-01-20 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_rename_pur_achat_id_alter_rawmaterial_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achat',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
