# Generated by Django 5.0.1 on 2024-01-21 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_alter_achat_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vente',
            name='id',
        ),
        migrations.AlterField(
            model_name='vente',
            name='num_vente',
            field=models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
