# Generated by Django 5.0.1 on 2024-01-21 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_delete_doit_pointage_employe'),
        ('app1', '0011_remove_vente_id_alter_vente_num_vente'),
    ]

    operations = [
    ]
