# Generated by Django 5.0.1 on 2024-01-21 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_merge_20240121_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='prix_Unit',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
