# Generated by Django 5.0.1 on 2024-01-21 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_transfer_prix_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='num_tr',
            field=models.CharField(auto_created=True, editable=False, max_length=10),
        ),
    ]
