# Generated by Django 5.0.1 on 2024-01-21 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_alter_transfer_num_tr'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transfer',
            name='num_tr',
            field=models.CharField(auto_created=True, editable=False, max_length=10),
        ),
    ]
