# Generated by Django 5.0.1 on 2024-01-21 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_transfer_id_alter_transfer_num_tr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='id',
        ),
        migrations.AlterField(
            model_name='transfer',
            name='num_tr',
            field=models.CharField(auto_created=True, editable=False, max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
