# Generated by Django 5.0.1 on 2024-01-21 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_remove_transfer_id_alter_transfer_num_tr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
