# Generated by Django 5.0.1 on 2024-01-21 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_alter_transfer_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transfer',
        ),
    ]
