# Generated by Django 5.0.1 on 2024-01-21 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_delete_transfer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('num_tr', models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('prix_Unit', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.centre')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.rawmaterial')),
            ],
        ),
    ]
