from django.contrib import admin
from .models import *
# Register your models here.
admin.site.register(RawMaterial)
admin.site.register(Client)
admin.site.register(Supplier)
admin.site.register(Centre)
admin.site.register(Employee)
admin.site.register(Achat)
admin.site.register(Transfer)
admin.site.register(Vente)
admin.site.register(Stock)
admin.site.register(Product)
admin.site.register(VenteP)
admin.site.register(Employe)
admin.site.register(PV)
admin.site.register(EnRapport)
# admin.site.register(Doit)
admin.site.register(Pointage)
admin.site.register(Massrouf)